In [1]:
import pandas as pd

In [2]:
path = "data/titanic.csv"
df = pd.read_csv(path)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
dfn = df[['Survived','Pclass','Sex','Age','Fare']]
dfn

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [4]:
inputs = dfn.drop(columns='Survived')
Target = dfn['Survived']
inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()

In [6]:
inputs['sex_n'] = le_sex.fit_transform(inputs['Sex'])
inputs = inputs.drop(columns='Sex')
inputs

     Pclass   Age     Fare  sex_n
0         3  22.0   7.2500      1
1         1  38.0  71.2833      0
2         3  26.0   7.9250      0
3         1  35.0  53.1000      0
4         3  35.0   8.0500      1
..      ...   ...      ...    ...
886       2  27.0  13.0000      1
887       1  19.0  30.0000      0
888       3   NaN  23.4500      0
889       1  26.0  30.0000      1
890       3  32.0   7.7500      1

[891 rows x 4 columns]

In [7]:
inputs = inputs[['Pclass', 'sex_n', 'Age', 'Fare']]

inputs

     Pclass  sex_n   Age     Fare
0         3      1  22.0   7.2500
1         1      0  38.0  71.2833
2         3      0  26.0   7.9250
3         1      0  35.0  53.1000
4         3      1  35.0   8.0500
..      ...    ...   ...      ...
886       2      1  27.0  13.0000
887       1      0  19.0  30.0000
888       3      0   NaN  23.4500
889       1      1  26.0  30.0000
890       3      1  32.0   7.7500

[891 rows x 4 columns]

In [8]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [9]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass  sex_n   Age     Fare
0       3      1  22.0   7.2500
1       1      0  38.0  71.2833
2       3      0  26.0   7.9250
3       1      0  35.0  53.1000
4       3      1  35.0   8.0500

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(inputs,Target,train_size=0.9)

In [11]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [12]:
model.fit(inputs,Target)

GaussianNB()

In [13]:
model.score(inputs, Target)

0.7777777777777778

In [14]:
model.predict([[1,1,40,30]])

array([0], dtype=int64)

In [15]:
model.predict_proba([[1,1,40,30]])

array([[0.77426306, 0.22573694]])

In [17]:
model.score(x_test,y_test)

0.7777777777777778

In [18]:
model.predict(x_test)

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1], dtype=int64)

In [19]:
model.predict_proba(x_test[:10])

array([[7.05042507e-01, 2.94957493e-01],
       [9.55858306e-01, 4.41416941e-02],
       [4.46892317e-11, 1.00000000e+00],
       [2.53474089e-03, 9.97465259e-01],
       [7.64325432e-01, 2.35674568e-01],
       [9.23890115e-01, 7.61098855e-02],
       [1.34235468e-02, 9.86576453e-01],
       [1.24452478e-02, 9.87554752e-01],
       [9.66315680e-01, 3.36843203e-02],
       [9.63673835e-01, 3.63261652e-02]])

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train, y_train, cv=5)

array([0.7515528, 0.8      , 0.8      , 0.6875   , 0.8125   ])

In [21]:
x_test

     Pclass  sex_n   Age      Fare
456       1      1  65.0   26.5500
352       3      1  15.0    7.2292
299       1      0  50.0  247.5208
581       1      0  39.0  110.8833
782       1      1  29.0   30.0000
..      ...    ...   ...       ...
775       3      1  18.0    7.7500
253       3      1  30.0   16.1000
436       3      0  21.0   34.3750
687       3      1  19.0   10.1708
56        2      0  21.0   10.5000

[90 rows x 4 columns]