In [5]:
import pandas as pd
path = "data/export.csv"
df = pd.read_csv(path)
df

     Pclass  sex_n        Age     Fare  Survived
0         3      1  22.000000   7.2500         0
1         1      0  38.000000  71.2833         1
2         3      0  26.000000   7.9250         1
3         1      0  35.000000  53.1000         1
4         3      1  35.000000   8.0500         0
..      ...    ...        ...      ...       ...
886       2      1  27.000000  13.0000         0
887       1      0  19.000000  30.0000         1
888       3      0  29.699118  23.4500         0
889       1      1  26.000000  30.0000         1
890       3      1  32.000000   7.7500         0

[891 rows x 5 columns]

In [6]:
df_0 = df[df['Survived']==0]
df_0

     Pclass  sex_n        Age     Fare  Survived
0         3      1  22.000000   7.2500         0
4         3      1  35.000000   8.0500         0
5         3      1  29.699118   8.4583         0
6         1      1  54.000000  51.8625         0
7         3      1   2.000000  21.0750         0
..      ...    ...        ...      ...       ...
884       3      1  25.000000   7.0500         0
885       3      0  39.000000  29.1250         0
886       2      1  27.000000  13.0000         0
888       3      0  29.699118  23.4500         0
890       3      1  32.000000   7.7500         0

[549 rows x 5 columns]

In [7]:
df_1 = df[df['Survived']==1]
df_1

     Pclass  sex_n   Age     Fare  Survived
1         1      0  38.0  71.2833         1
2         3      0  26.0   7.9250         1
3         1      0  35.0  53.1000         1
8         3      0  27.0  11.1333         1
9         2      0  14.0  30.0708         1
..      ...    ...   ...      ...       ...
875       3      0  15.0   7.2250         1
879       1      0  56.0  83.1583         1
880       2      0  25.0  26.0000         1
887       1      0  19.0  30.0000         1
889       1      1  26.0  30.0000         1

[342 rows x 5 columns]

**Defining the Gaussian likelihood function**

In [15]:
import numpy as np

def gaussian_likelihood(x, mean, std):
    """Calculate the Gaussian likelihood"""
    exponent = np.exp(-((x - mean) ** 2) / (2 * std ** 2))
    return (1 / (np.sqrt(2 * np.pi) * std)) * exponent

**Calculating the likelihood for each feature in df_0 and df_1**|

In [16]:
df_0['P(Pclass)'] = gaussian_likelihood(df_0['Pclass'], df_0['Pclass'].mean(), df_0['Pclass'].std())
df_0['P(sex_n)'] = gaussian_likelihood(df_0['sex_n'], df_0['sex_n'].mean(), df_0['sex_n'].std())
df_0['P(Age)'] = gaussian_likelihood(df_0['Age'], df_0['Age'].mean(), df_0['Age'].std())
df_0['P(Fare)'] = gaussian_likelihood(df_0['Fare'], df_0['Fare'].mean(), df_0['Fare'].std())

df_1['P(Pclass)'] = gaussian_likelihood(df_1['Pclass'], df_1['Pclass'].mean(), df_1['Pclass'].std())
df_1['P(sex_n)'] = gaussian_likelihood(df_1['sex_n'], df_1['sex_n'].mean(), df_1['sex_n'].std())
df_1['P(Age)'] = gaussian_likelihood(df_1['Age'], df_1['Age'].mean(), df_1['Age'].std())
df_1['P(Fare)'] = gaussian_likelihood(df_1['Fare'], df_1['Fare'].mean(), df_1['Fare'].std())

In [17]:
df_0

,Pclass,sex_n,Age,Fare,Survived,P(Pclass),P(sex_n),P(Age),P(Fare)
0,3,1,22.000000,7.2500,0,0.442848,1.030876,0.025492,0.011361
4,3,1,35.000000,8.0500,0,0.442848,1.030876,0.029927,0.011495
5,3,1,29.699118,8.4583,0,0.442848,1.030876,0.031972,0.011562
6,1,1,54.000000,51.8625,0,0.062081,1.030876,0.005335,0.008112
7,3,1,2.000000,21.0750,0,0.442848,1.030876,0.002375,0.012703
...,...,...,...,...,...,...,...,...,...
884,3,1,25.000000,7.0500,0,0.442848,1.030876,0.029138,0.011327
885,3,0,39.000000,29.1250,0,0.442848,0.062861,0.025256,0.012397
886,2,1,27.000000,13.0000,0,0.417528,1.030876,0.030844,0.012185
888,3,0,29.699118,23.4500,0,0.442848,0.062861,0.031972,0.012699
890,3,1,32.000000,7.7500,0,0.442848,1.030876,0.031766,0.011446

In [18]:
df_1

,Pclass,sex_n,Age,Fare,Survived,P(Pclass),P(sex_n),P(Age),P(Fare)
1,1,0,38.0,71.2833,1,0.252136,0.677052,0.022891,0.005647
2,3,0,26.0,7.9250,1,0.220652,0.677052,0.028474,0.004980
3,1,0,35.0,53.1000,1,0.252136,0.677052,0.025958,0.005975
8,3,0,27.0,11.1333,1,0.220652,0.677052,0.028784,0.005122
9,2,0,14.0,30.0708,1,0.461337,0.677052,0.016579,0.005768
...,...,...,...,...,...,...,...,...,...
875,3,0,15.0,7.2250,1,0.220652,0.677052,0.017853,0.004948
879,1,0,56.0,83.1583,1,0.252136,0.677052,0.003974,0.005227
880,2,0,25.0,26.0000,1,0.461337,0.677052,0.028020,0.005661
887,1,0,19.0,30.0000,1,0.252136,0.677052,0.022777,0.005766
889,1,1,26.0,30.0000,1,0.252136,0.294503,0.028474,0.005766

In [19]:
inputs = pd.read_csv("data/inputs.csv")
inputs

     Pclass  sex_n        Age     Fare
0         3      1  22.000000   7.2500
1         1      0  38.000000  71.2833
2         3      0  26.000000   7.9250
3         1      0  35.000000  53.1000
4         3      1  35.000000   8.0500
..      ...    ...        ...      ...
886       2      1  27.000000  13.0000
887       1      0  19.000000  30.0000
888       3      0  29.699118  23.4500
889       1      1  26.000000  30.0000
890       3      1  32.000000   7.7500

[891 rows x 4 columns]

**Calculating the Priors**

In [23]:
n_survived = len(df_1)
n_not_survived = len(df_0)

total = len(inputs)

p_survived = n_survived / total
p_not_survived = n_not_survived / total

**Unnormalized posterior by class**

In [24]:
# For df_0 (Survived = 0)
df_0['P(Survived=0 | X)'] = df_0['P(Pclass)'] * df_0['P(sex_n)'] * df_0['P(Age)'] * df_0['P(Fare)'] * p_not_survived

# For df_1 (Survived = 1)
df_1['P(Survived=1 | X)'] = df_1['P(Pclass)'] * df_1['P(sex_n)'] * df_1['P(Age)'] * df_1['P(Fare)'] * p_survived

In [26]:
df_1

,Pclass,sex_n,Age,Fare,Survived,P(Pclass),P(sex_n),P(Age),P(Fare),P(Survived=1 | X)
1,1,0,38.0,71.2833,1,0.252136,0.677052,0.022891,0.005647,0.000008
2,3,0,26.0,7.9250,1,0.220652,0.677052,0.028474,0.004980,0.000008
3,1,0,35.0,53.1000,1,0.252136,0.677052,0.025958,0.005975,0.000010
8,3,0,27.0,11.1333,1,0.220652,0.677052,0.028784,0.005122,0.000008
9,2,0,14.0,30.0708,1,0.461337,0.677052,0.016579,0.005768,0.000011
...,...,...,...,...,...,...,...,...,...,...
875,3,0,15.0,7.2250,1,0.220652,0.677052,0.017853,0.004948,0.000005
879,1,0,56.0,83.1583,1,0.252136,0.677052,0.003974,0.005227,0.000001
880,2,0,25.0,26.0000,1,0.461337,0.677052,0.028020,0.005661,0.000019
887,1,0,19.0,30.0000,1,0.252136,0.677052,0.022777,0.005766,0.000009
889,1,1,26.0,30.0000,1,0.252136,0.294503,0.028474,0.005766,0.000005

In [47]:
df_0

,Pclass,sex_n,Age,Fare,Survived,P(Pclass),P(sex_n),P(Age),P(Fare),P(Survived=0 | X)
0,3,1,22.000000,7.2500,0,0.442848,1.030876,0.025492,0.011361,0.000081
4,3,1,35.000000,8.0500,0,0.442848,1.030876,0.029927,0.011495,0.000097
5,3,1,29.699118,8.4583,0,0.442848,1.030876,0.031972,0.011562,0.000104
6,1,1,54.000000,51.8625,0,0.062081,1.030876,0.005335,0.008112,0.000002
7,3,1,2.000000,21.0750,0,0.442848,1.030876,0.002375,0.012703,0.000008
...,...,...,...,...,...,...,...,...,...,...
884,3,1,25.000000,7.0500,0,0.442848,1.030876,0.029138,0.011327,0.000093
885,3,0,39.000000,29.1250,0,0.442848,0.062861,0.025256,0.012397,0.000005
886,2,1,27.000000,13.0000,0,0.417528,1.030876,0.030844,0.012185,0.000100
888,3,0,29.699118,23.4500,0,0.442848,0.062861,0.031972,0.012699,0.000007
890,3,1,32.000000,7.7500,0,0.442848,1.030876,0.031766,0.011446,0.000102

**Normalized posterior probabilities**

In [51]:
df_combined.to_excel("data/combined.xlsx",index=False)