# Updating rows and columns

In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [6]:
df.columns=['first_name', 'last_name', 'email']

In [7]:
df

  first_name last_name                    email
0      Corey   Schafer  person007@example.com
1       Jane       Doe        person014@example.com
2       John       Doe        person015@example.com

In [8]:
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  person007@example.com
1       Jane       Doe        person014@example.com
2       John       Doe        person015@example.com

In [9]:
df.columns = df.columns.str.replace('_','')
df

  FIRSTNAME LASTNAME                    EMAIL
0     Corey  Schafer  person007@example.com
1      Jane      Doe        person014@example.com
2      John      Doe        person015@example.com

In [10]:
df.columns = df.columns.str.replace('','_')
df

  _F_I_R_S_T_N_A_M_E_ _L_A_S_T_N_A_M_E_              _E_M_A_I_L_
0               Corey           Schafer  person007@example.com
1                Jane               Doe        person014@example.com
2                John               Doe        person015@example.com

In [11]:
df.columns = [x.lower() for x in df.columns]
df.columns = df.columns.str.replace('_','')
df

  firstname lastname                    email
0     Corey  Schafer  person007@example.com
1      Jane      Doe        person014@example.com
2      John      Doe        person015@example.com

In [12]:
df.rename(columns={'firstname':'first','lastname':'last'})

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [13]:
df

  firstname lastname                    email
0     Corey  Schafer  person007@example.com
1      Jane      Doe        person014@example.com
2      John      Doe        person015@example.com

In [14]:
df.rename(columns={'firstname':'first','lastname':'last'},inplace=True)

In [15]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [16]:
df.loc[2]

first                 John
last                   Doe
email    person015@example.com
Name: 2, dtype: object

In [17]:
df.loc[2]=['John','Smith','person017@example.com']

In [18]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith      person017@example.com

In [19]:
df.loc[2,['last','email']]

last                   Smith
email    person017@example.com
Name: 2, dtype: object

In [20]:
df.loc[2,['last','email']]=['Doe','person015@example.com']

In [21]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [22]:
df.loc[2,'last']='Smith'

In [23]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith        person015@example.com

In [24]:
df.at[2,'last']='Doe'

In [25]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [26]:
filt=(df['email']=='person015@example.com')
df[filt]

  first last              email
2  John  Doe  person015@example.com

In [27]:
df[filt]['last']

2    Doe
Name: last, dtype: object

In [28]:
df[filt]['last']='Smith'

In [29]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [30]:
filt=(df['email']=='person015@example.com')
df.loc[filt,'last']='Smith'

In [31]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith        person015@example.com

In [32]:
df['email'].str.lower()

0    person021@example.com
1          person023@example.com
2          person024@example.com
Name: email, dtype: object

In [33]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith        person015@example.com

In [34]:
df['email']=df['email'].str.lower()

In [35]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [36]:
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [37]:
def update_email(email):
    return email.upper()

In [38]:
df['email'].apply(update_email)

0    person003@example.com
1          person011@example.com
2          person012@example.com
Name: email, dtype: object

In [39]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [40]:
df['email']=df['email'].apply(update_email)

In [41]:
df

   first     last                    email
0  Corey  Schafer  person003@example.com
1   Jane      Doe        person011@example.com
2   John    Smith        person012@example.com

In [42]:
df['email']=df['email'].apply(lambda x: x.lower())

In [43]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [44]:
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [45]:
df.apply(len)

first    3
last     3
email    3
dtype: int64

In [46]:
len(df['email'])

3

In [47]:
df.apply(len,axis='columns')

0    3
1    3
2    3
dtype: int64

In [48]:
df.apply(pd.Series.min)

first                      Corey
last                         Doe
email    person021@example.com
dtype: object

In [49]:
df.apply(pd.Series.min,axis="columns")

0    Corey
1      Doe
2     John
dtype: object

In [50]:
df.apply(lambda x: x.min())

first                      Corey
last                         Doe
email    person021@example.com
dtype: object

In [51]:
df.applymap(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     5     17

In [52]:
df.applymap(str.lower)

   first     last                    email
0  corey  schafer  person021@example.com
1   jane      doe        person023@example.com
2   john    smith        person024@example.com

In [53]:
df['first'].map({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

In [54]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [55]:
df['first'].replace({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2     John
Name: first, dtype: object

In [56]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [57]:
df['first']= df['first'].map({'Corey':'Chris','Jane':'Mary'})

In [58]:
df

   first     last                    email
0  Chris  Schafer  person021@example.com
1   Mary      Doe        person023@example.com
2    NaN    Smith        person024@example.com