# Missing values and data types

In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    "first": ["Corey", 'Jane', 'John','Chris',np.nan, None,'NA'], 
    "last": ["Schafer", 'Doe', 'Doe','Schafer',np.nan,np.nan,'Missing'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com',None,np.nan,'person002@example.com','NA'],
    "age": ['33','55','63','36',None,None,'Missing']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      person002@example.com     None
6     NA  Missing                       NA  Missing

In [5]:
df.dropna()

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
6     NA  Missing                       NA  Missing

In [6]:
df.dropna(axis='index',how='any')

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
6     NA  Missing                       NA  Missing

In [7]:
df.dropna(axis='index',how='all')

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
3  Chris  Schafer                     None       36
5   None      NaN      person002@example.com     None
6     NA  Missing                       NA  Missing

In [8]:
df.dropna(axis='columns',how='all')

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      person002@example.com     None
6     NA  Missing                       NA  Missing

In [9]:
df.dropna(axis='columns',how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [10]:
df.dropna(axis='index',how='all',subset=['email'])

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
5   None      NaN      person002@example.com     None
6     NA  Missing                       NA  Missing

In [11]:
df.dropna(axis='index',how='all',subset=['last','email'])

   first     last                    email      age
0  Corey  Schafer  person007@example.com       33
1   Jane      Doe        person014@example.com       55
2   John      Doe        person015@example.com       63
3  Chris  Schafer                     None       36
5   None      NaN      person002@example.com     None
6     NA  Missing                       NA  Missing

In [12]:
people = {
    "first": ["Corey", 'Jane', 'John','Chris',np.nan, None,'NA'], 
    "last": ["Schafer", 'Doe', 'Doe','Schafer',np.nan,np.nan,'Missing'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com',None,np.nan,'person002@example.com','NA'],
    "age": ['33','55','63','36',None,None,'Missing']
}

In [13]:
df = pd.DataFrame(people)
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)

In [14]:
df

   first     last                    email   age
0  Corey  Schafer  person007@example.com    33
1   Jane      Doe        person014@example.com    55
2   John      Doe        person015@example.com    63
3  Chris  Schafer                     None    36
4    NaN      NaN                      NaN  None
5   None      NaN      person002@example.com  None
6    NaN      NaN                      NaN   NaN

In [15]:
df.dropna()

   first     last                    email age
0  Corey  Schafer  person007@example.com  33
1   Jane      Doe        person014@example.com  55
2   John      Doe        person015@example.com  63

In [16]:
df.dropna(axis='index',how='all',subset=['last','email'])

   first     last                    email   age
0  Corey  Schafer  person007@example.com    33
1   Jane      Doe        person014@example.com    55
2   John      Doe        person015@example.com    63
3  Chris  Schafer                     None    36
5   None      NaN      person002@example.com  None

In [17]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [18]:
df.fillna('MISSING')

     first     last                    email      age
0    Corey  Schafer  person007@example.com       33
1     Jane      Doe        person014@example.com       55
2     John      Doe        person015@example.com       63
3    Chris  Schafer                  MISSING       36
4  MISSING  MISSING                  MISSING  MISSING
5  MISSING  MISSING      person002@example.com  MISSING
6  MISSING  MISSING                  MISSING  MISSING

In [19]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  person007@example.com  33
1   Jane      Doe        person014@example.com  55
2   John      Doe        person015@example.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      person002@example.com   0
6      0        0                        0   0

In [20]:
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [21]:
pd.to_numeric(df['age'], errors='coerce').mean()

46.75

In [22]:
type(np.nan)

float

In [23]:
df['age'] = pd.to_numeric(df['age'], errors='coerce').astype('Int64')

In [24]:
df['age'] = df['age'].astype(float)

In [25]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [26]:
pd.to_numeric(df['age'], errors='coerce').mean()

46.75