In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [6]:
df.columns = ['first_name', 'last_name', 'email']

In [7]:
df

  first_name last_name                    email
0      Corey   Schafer  person007@example.com
1       Jane       Doe        person014@example.com
2       John       Doe        person015@example.com

In [8]:
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  person007@example.com
1       Jane       Doe        person014@example.com
2       John       Doe        person015@example.com

In [9]:
df.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)

In [10]:
df.loc[2] = ['John', 'Smith', 'person017@example.com']

In [11]:
df.loc[2, ['last', 'email']] = ['Doe', 'person015@example.com']

In [12]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [13]:
df.loc[2, 'last'] = 'Smith'

In [14]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith        person015@example.com

In [15]:
df.at[2, 'last'] = 'Doe'

In [16]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [17]:
filt = (df['email'] == 'person015@example.com')
df[filt]['last'] = 'Smith'

In [18]:
filt = (df['email'] == 'person015@example.com')
df.loc[filt, 'last'] = 'Smith'

In [19]:
df['email'] = df['email'].str.lower()

In [20]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [21]:
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [22]:
def update_email(email):
    return email.upper()

In [23]:
df['email'].apply(update_email)

0    person003@example.com
1          person011@example.com
2          person012@example.com
Name: email, dtype: object

In [24]:
df['email'] = df['email'].apply(update_email)

In [25]:
df

   first     last                    email
0  Corey  Schafer  person003@example.com
1   Jane      Doe        person011@example.com
2   John    Smith        person012@example.com

In [26]:
df['email'] = df['email'].apply(lambda x: x.lower())

In [27]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person024@example.com

In [28]:
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [29]:
df.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [30]:
len(df['email'])

3

In [31]:
df.apply(pd.Series.min)

first                      Corey
last                         Doe
email    person021@example.com
dtype: object

In [32]:
df.apply(lambda x: x.min())

first                      Corey
last                         Doe
email    person021@example.com
dtype: object

In [33]:
df.applymap(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     5     17

In [34]:
df.applymap(str.lower)

   first     last                    email
0  corey  schafer  person021@example.com
1   jane      doe        person023@example.com
2   john    smith        person024@example.com

In [35]:
df['first'].map({'Corey': 'Chris', 'Jane': 'Mary'})

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

In [36]:
df['first'] = df['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})

In [37]:
df

   first     last                    email
0  Chris  Schafer  person021@example.com
1   Mary      Doe        person023@example.com
2   John    Smith        person024@example.com