In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
people['email']

['person007@example.com', 'person014@example.com', 'person015@example.com']

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [6]:
df['email']

0    person007@example.com
1          person014@example.com
2          person015@example.com
Name: email, dtype: object

In [7]:
type(df['email'])

pandas.core.series.Series

In [8]:
df.email

0    person007@example.com
1          person014@example.com
2          person015@example.com
Name: email, dtype: object

In [9]:
df[['last','email']]

      last                    email
0  Schafer  person007@example.com
1      Doe        person014@example.com
2      Doe        person015@example.com

In [10]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [11]:
df.iloc[0]

first                      Corey
last                     Schafer
email    person007@example.com
Name: 0, dtype: object

In [12]:
df.iloc[[0,1]]

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com

In [13]:
df.iloc[[0,1],2]

0    person007@example.com
1          person014@example.com
Name: email, dtype: object

In [14]:
df.loc[0]

first                      Corey
last                     Schafer
email    person007@example.com
Name: 0, dtype: object

In [15]:
df.loc[[0,1],'email']

0    person007@example.com
1          person014@example.com
Name: email, dtype: object

In [16]:
df.loc[[0,1],['email','last']]

                     email     last
0  person007@example.com  Schafer
1        person014@example.com      Doe

In [17]:
df.set_index('email')

                         first     last
email
person007@example.com  Corey  Schafer
person014@example.com         Jane      Doe
person015@example.com         John      Doe

In [18]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [19]:
df.set_index('email',inplace=True)
df

                         first     last
email
person007@example.com  Corey  Schafer
person014@example.com         Jane      Doe
person015@example.com         John      Doe

In [20]:
df.loc['person007@example.com','last']

'Schafer'

In [21]:
df.iloc[0]

first      Corey
last     Schafer
Name: person007@example.com, dtype: object

In [22]:
df.reset_index(inplace=True)
df

                     email  first     last
0  person007@example.com  Corey  Schafer
1        person014@example.com   Jane      Doe
2        person015@example.com   John      Doe

In [23]:
df

                     email  first     last
0  person007@example.com  Corey  Schafer
1        person014@example.com   Jane      Doe
2        person015@example.com   John      Doe

In [24]:
df['last']=='Doe'

0    False
1     True
2     True
Name: last, dtype: bool

In [25]:
filt = (df['last']=='Doe')

In [26]:
df[filt]

               email first last
1  person014@example.com  Jane  Doe
2  person015@example.com  John  Doe

In [27]:
df.loc[filt,'email']

1    person014@example.com
2    person015@example.com
Name: email, dtype: object

In [28]:
filtr=(df['last']=='Doe') & (df['first']=='John')

In [29]:
df[filtr]

               email first last
2  person015@example.com  John  Doe

In [30]:
df.loc[filtr,'email']

2    person015@example.com
Name: email, dtype: object

In [31]:
filtr2=(df['last']=='Schafer') | (df['first']=='John')
df.loc[filtr2,'email']

0    person007@example.com
2          person015@example.com
Name: email, dtype: object

In [32]:
df.loc[-filtr2,'email']

1    person014@example.com
Name: email, dtype: object

In [33]:
df

                     email  first     last
0  person007@example.com  Corey  Schafer
1        person014@example.com   Jane      Doe
2        person015@example.com   John      Doe

In [34]:
df.columns

Index(['email', 'first', 'last'], dtype='object')

In [35]:
df.columns=['first_name','last_name','email']

In [36]:
df

                first_name last_name    email
0  person007@example.com     Corey  Schafer
1        person014@example.com      Jane      Doe
2        person015@example.com      John      Doe

In [37]:
df.columns=[x.upper() for x in df.columns]
df

                FIRST_NAME LAST_NAME    EMAIL
0  person007@example.com     Corey  Schafer
1        person014@example.com      Jane      Doe
2        person015@example.com      John      Doe

In [38]:
df.columns = df.columns.str.replace('_',' ')
df

                FIRST NAME LAST NAME    EMAIL
0  person007@example.com     Corey  Schafer
1        person014@example.com      Jane      Doe
2        person015@example.com      John      Doe

In [39]:
df.columns=[x.upper() for x in df.columns]
df.columns=['first_name','last_name','email']
df

                first_name last_name    email
0  person007@example.com     Corey  Schafer
1        person014@example.com      Jane      Doe
2        person015@example.com      John      Doe

In [40]:
df.rename(columns={'first_name':'first','last_name':'last'})

                     first   last    email
0  person007@example.com  Corey  Schafer
1        person014@example.com   Jane      Doe
2        person015@example.com   John      Doe

In [41]:
df

                first_name last_name    email
0  person007@example.com     Corey  Schafer
1        person014@example.com      Jane      Doe
2        person015@example.com      John      Doe

In [42]:
df.rename(columns={'first_name':'first','last_name':'last'},inplace=True)

In [43]:
df

                     first   last    email
0  person007@example.com  Corey  Schafer
1        person014@example.com   Jane      Doe
2        person015@example.com   John      Doe

In [44]:
df.loc[2]=['John','Smith',"person018@example.com"]
df.loc[0]=['Corey','Schafer',"person008@example.com"]
df.loc[1]=['Jane','Doe',"person014@example.com"]
df

   first     last                   email
0  Corey  Schafer  person008@example.com
1   Jane      Doe       person014@example.com
2   John    Smith     person018@example.com

In [45]:
df.loc[2,['last','email']]=['Doe','person015@example.com']
df

   first     last                   email
0  Corey  Schafer  person008@example.com
1   Jane      Doe       person014@example.com
2   John      Doe       person015@example.com

In [46]:
df.loc[2,'last']='Smith'
df

   first     last                   email
0  Corey  Schafer  person008@example.com
1   Jane      Doe       person014@example.com
2   John    Smith       person015@example.com

In [47]:
df.at[2,'last']='Doe'
df

   first     last                   email
0  Corey  Schafer  person008@example.com
1   Jane      Doe       person014@example.com
2   John      Doe       person015@example.com

In [48]:
filtrr = (df['email']=='person016@example.com')
df[filtrr]['last']='Smith'

In [49]:
df

   first     last                   email
0  Corey  Schafer  person008@example.com
1   Jane      Doe       person014@example.com
2   John      Doe       person015@example.com

In [50]:
filtrr = (df['email']=='person016@example.com')
df.loc[filtrr,'last']='Smith'

In [51]:
df

   first     last                   email
0  Corey  Schafer  person008@example.com
1   Jane      Doe       person014@example.com
2   John      Doe       person015@example.com

In [52]:
df['email'].str.lower()

0    person022@example.com
1         person023@example.com
2         person024@example.com
Name: email, dtype: object

In [53]:
df['email']=df['email'].str.lower()
df

   first     last                   email
0  Corey  Schafer  person022@example.com
1   Jane      Doe       person023@example.com
2   John      Doe       person024@example.com

In [54]:
df['email'].apply(len)

0    22
1    17
2    17
Name: email, dtype: int64

In [55]:
def update_email(email):
    return email.upper()

In [56]:
df['email'].apply(update_email)

0    person004@example.com
1         person011@example.com
2         person012@example.com
Name: email, dtype: object

In [57]:
df['email']=df['email'].apply(update_email)
df

   first     last                   email
0  Corey  Schafer  person004@example.com
1   Jane      Doe       person011@example.com
2   John      Doe       person012@example.com

In [58]:
df

   first     last                   email
0  Corey  Schafer  person004@example.com
1   Jane      Doe       person011@example.com
2   John      Doe       person012@example.com

In [59]:
df['email']=df['email'].apply(lambda x: x.lower())
df

   first     last                   email
0  Corey  Schafer  person022@example.com
1   Jane      Doe       person023@example.com
2   John      Doe       person024@example.com

In [60]:
df['email'].apply(len)

0    22
1    17
2    17
Name: email, dtype: int64

In [61]:
df.apply(len)

first    3
last     3
email    3
dtype: int64

In [62]:
len(df['email'])

3

In [63]:
df.apply(len,axis='columns')

0    3
1    3
2    3
dtype: int64

In [64]:
df.apply(pd.Series.min)

first                     Corey
last                        Doe
email    person022@example.com
dtype: object

In [65]:
df.apply(lambda x: x.min())

first                     Corey
last                        Doe
email    person022@example.com
dtype: object

In [66]:
df.applymap(len)

   first  last  email
0      5     7     22
1      4     3     17
2      4     3     17

In [67]:
df.applymap(str.lower)

   first     last                   email
0  corey  schafer  person022@example.com
1   jane      doe       person023@example.com
2   john      doe       person024@example.com

In [68]:
df['first'].map({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

In [69]:
df['first'].replace({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2     John
Name: first, dtype: object

In [70]:
df['first']=df['first'].replace({'Corey':'Chris','Jane':'Mary'})
df

   first     last                   email
0  Chris  Schafer  person022@example.com
1   Mary      Doe       person023@example.com
2   John      Doe       person024@example.com