In [2]:
import pandas as pd

data = [
    [5, 0, 0, 0, 0, 3477.702],
    [5, 0, 0, 0, 0, 6955.404],
    [5, 0, 0, 0, 0, 10433.1061],
    [5, 0, 0, 0, 0, 13910.8081],
    [5, 0, 0, 0, 0, 17388.5101],
    [5, 0, 0, 0, 0, 20866.2121],
    [5, 0, 0.05, 1.5, 0, 3477.702],
    [5, 0, 0.05, 1.5, 0, 6955.404],
    [5, 0, 0.05, 1.5, 0, 10433.1061],
    [5, 0, 0.05, 1.5, 0, 13910.8081],
    [5, 0, 0.05, 1.5, 0, 17388.5101],
    [5, 0, 0.05, 1.5, 0, 20866.2121],
    [5, 0, 0.1, 1.5, 0, 3477.702],
    [5, 0, 0.1, 1.5, 0, 6955.404],
    [5, 0, 0.1, 1.5, 0, 10433.1061],
    [5, 0, 0.1, 1.5, 0, 13910.8081],
    [5, 0, 0.1, 1.5, 0, 17388.5101],
    [5, 0, 0.1, 1.5, 0, 20866.2121],
    [5, 0, 0.05, 1, 1, 3477.702],
    [5, 0, 0.05, 1, 1, 6955.404],
    [5, 0, 0.05, 1, 1, 10433.1061],
    [5, 0, 0.05, 1, 1, 13910.8081],
    [5, 0, 0.05, 1, 1, 17388.5101],
    [5, 0, 0.05, 1, 1, 20866.2121],
    [5, 0, 0.1, 1, 1, 3477.702],
    [5, 0, 0.1, 1, 1, 6955.404],
    [5, 0, 0.1, 1, 1, 10433.1061],
    [5, 0, 0.1, 1, 1, 13910.8081],
    [5, 0, 0.1, 1, 1, 17388.5101]
]

columns = ['Col1', 'Col2', 'Col3', 'Col4', 'Col5', 'Value']

df = pd.DataFrame(data, columns=columns)

df.to_excel("data/Nusseltdata.xlsx", index=False)

In [3]:
new_data = [
    [5, 0, 0.1, 1, 1, 20866.2121],
    [5, 0.5, 0, 0, 0, 3477.702],
    [5, 0.5, 0, 0, 0, 6955.404],
    [5, 0.5, 0, 0, 0, 10433.1061]
]

new_df = pd.DataFrame(new_data, columns=['Col1', 'Col2', 'Col3', 'Col4', 'Col5', 'Value'])

df = pd.concat([df, new_df], ignore_index=True)

In [4]:
df

    Col1  Col2  Col3  Col4  Col5       Value
0      5   0.0  0.00   0.0     0   3477.7020
1      5   0.0  0.00   0.0     0   6955.4040
2      5   0.0  0.00   0.0     0  10433.1061
3      5   0.0  0.00   0.0     0  13910.8081
4      5   0.0  0.00   0.0     0  17388.5101
5      5   0.0  0.00   0.0     0  20866.2121
6      5   0.0  0.05   1.5     0   3477.7020
7      5   0.0  0.05   1.5     0   6955.4040
8      5   0.0  0.05   1.5     0  10433.1061
9      5   0.0  0.05   1.5     0  13910.8081
10     5   0.0  0.05   1.5     0  17388.5101
11     5   0.0  0.05   1.5     0  20866.2121
12     5   0.0  0.10   1.5     0   3477.7020
13     5   0.0  0.10   1.5     0   6955.4040
14     5   0.0  0.10   1.5     0  10433.1061
15     5   0.0  0.10   1.5     0  13910.8081
16     5   0.0  0.10   1.5     0  17388.5101
17     5   0.0  0.10   1.5     0  20866.2121
18     5   0.0  0.05   1.0     1   3477.7020
19     5   0.0  0.05   1.0     1   6955.4040
20     5   0.0  0.05   1.0     1  10433.1061
21     5   0.0  0.05   1.0     1  13910.8081
22     5   0.0  0.05   1.0     1  17388.5101
23     5   0.0  0.05   1.0     1  20866.2121
24     5   0.0  0.10   1.0     1   3477.7020
25     5   0.0  0.10   1.0     1   6955.4040
26     5   0.0  0.10   1.0     1  10433.1061
27     5   0.0  0.10   1.0     1  13910.8081
28     5   0.0  0.10   1.0     1  17388.5101
29     5   0.0  0.10   1.0     1  20866.2121
30     5   0.5  0.00   0.0     0   3477.7020
31     5   0.5  0.00   0.0     0   6955.4040
32     5   0.5  0.00   0.0     0  10433.1061

In [6]:
df = df.drop(df.index[33:60])

In [7]:
df

    Col1  Col2  Col3  Col4  Col5       Value
0      5   0.0  0.00   0.0   0.0   3477.7020
1      5   0.0  0.00   0.0   0.0   6955.4040
2      5   0.0  0.00   0.0   0.0  10433.1061
3      5   0.0  0.00   0.0   0.0  13910.8081
4      5   0.0  0.00   0.0   0.0  17388.5101
5      5   0.0  0.00   0.0   0.0  20866.2121
6      5   0.0  0.05   1.5   0.0   3477.7020
7      5   0.0  0.05   1.5   0.0   6955.4040
8      5   0.0  0.05   1.5   0.0  10433.1061
9      5   0.0  0.05   1.5   0.0  13910.8081
10     5   0.0  0.05   1.5   0.0  17388.5101
11     5   0.0  0.05   1.5   0.0  20866.2121
12     5   0.0  0.10   1.5   0.0   3477.7020
13     5   0.0  0.10   1.5   0.0   6955.4040
14     5   0.0  0.10   1.5   0.0  10433.1061
15     5   0.0  0.10   1.5   0.0  13910.8081
16     5   0.0  0.10   1.5   0.0  17388.5101
17     5   0.0  0.10   1.5   0.0  20866.2121
18     5   0.0  0.05   1.0   1.0   3477.7020
19     5   0.0  0.05   1.0   1.0   6955.4040
20     5   0.0  0.05   1.0   1.0  10433.1061
21     5   0.0  0.05   1.0   1.0  13910.8081
22     5   0.0  0.05   1.0   1.0  17388.5101
23     5   0.0  0.05   1.0   1.0  20866.2121
24     5   0.0  0.10   1.0   1.0   3477.7020
25     5   0.0  0.10   1.0   1.0   6955.4040
26     5   0.0  0.10   1.0   1.0  10433.1061
27     5   0.0  0.10   1.0   1.0  13910.8081
28     5   0.0  0.10   1.0   1.0  17388.5101
29     5   0.0  0.10   1.0   1.0  20866.2121
30     5   0.5  0.00   0.0   0.0   3477.7020
31     5   0.5  0.00   0.0   0.0   6955.4040
32     5   0.5  0.00   0.0   0.0  10433.1061

In [8]:
data = {
    'Col1': [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    'Col2': [0.1, 0.2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    'Col3': [0.05, 0.1, 0.0, 0.0, 0.0, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
    'Col4': [1.5, 1.0, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
    'Col5': [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'Value': [10433.1061, 17388.5101, 13910.8081, 17388.5101, 20866.2121, 3477.7020, 6955.4040, 10433.1061, 
              13910.8081, 17388.5101, 20866.2121, 3477.7020, 6955.4040, 10433.1061, 13910.8081, 17388.5101, 
              20866.2121, 3477.7020, 6955.4040, 10433.1061, 13910.8081, 17388.5101, 20866.2121, 3477.7020, 
              6955.4040, 10433.1061, 13910.8081, 17388.5101]
}

df_new = pd.DataFrame(data)

df = pd.concat([df,df_new], ignore_index=True)

df

    Col1  Col2  Col3  Col4  Col5       Value
0      5   0.0   0.0   0.0   0.0   3477.7020
1      5   0.0   0.0   0.0   0.0   6955.4040
2      5   0.0   0.0   0.0   0.0  10433.1061
3      5   0.0   0.0   0.0   0.0  13910.8081
4      5   0.0   0.0   0.0   0.0  17388.5101
..   ...   ...   ...   ...   ...         ...
56     5   0.5   0.1   1.0   0.0   3477.7020
57     5   0.5   0.1   1.0   0.0   6955.4040
58     5   0.5   0.1   1.0   0.0  10433.1061
59     5   0.5   0.1   1.0   0.0  13910.8081
60     5   0.5   0.1   1.0   0.0  17388.5101

[61 rows x 6 columns]

In [9]:
pd.set_option('display.max_rows',62)

In [10]:
df

    Col1  Col2  Col3  Col4  Col5       Value
0      5   0.0  0.00   0.0   0.0   3477.7020
1      5   0.0  0.00   0.0   0.0   6955.4040
2      5   0.0  0.00   0.0   0.0  10433.1061
3      5   0.0  0.00   0.0   0.0  13910.8081
4      5   0.0  0.00   0.0   0.0  17388.5101
5      5   0.0  0.00   0.0   0.0  20866.2121
6      5   0.0  0.05   1.5   0.0   3477.7020
7      5   0.0  0.05   1.5   0.0   6955.4040
8      5   0.0  0.05   1.5   0.0  10433.1061
9      5   0.0  0.05   1.5   0.0  13910.8081
10     5   0.0  0.05   1.5   0.0  17388.5101
11     5   0.0  0.05   1.5   0.0  20866.2121
12     5   0.0  0.10   1.5   0.0   3477.7020
13     5   0.0  0.10   1.5   0.0   6955.4040
14     5   0.0  0.10   1.5   0.0  10433.1061
15     5   0.0  0.10   1.5   0.0  13910.8081
16     5   0.0  0.10   1.5   0.0  17388.5101
17     5   0.0  0.10   1.5   0.0  20866.2121
18     5   0.0  0.05   1.0   1.0   3477.7020
19     5   0.0  0.05   1.0   1.0   6955.4040
20     5   0.0  0.05   1.0   1.0  10433.1061
21     5   0.0  0.05   1.0   1.0  13910.8081
22     5   0.0  0.05   1.0   1.0  17388.5101
23     5   0.0  0.05   1.0   1.0  20866.2121
24     5   0.0  0.10   1.0   1.0   3477.7020
25     5   0.0  0.10   1.0   1.0   6955.4040
26     5   0.0  0.10   1.0   1.0  10433.1061
27     5   0.0  0.10   1.0   1.0  13910.8081
28     5   0.0  0.10   1.0   1.0  17388.5101
29     5   0.0  0.10   1.0   1.0  20866.2121
30     5   0.5  0.00   0.0   0.0   3477.7020
31     5   0.5  0.00   0.0   0.0   6955.4040
32     5   0.5  0.00   0.0   0.0  10433.1061
33     5   0.1  0.05   1.5   1.0  10433.1061
34     5   0.2  0.10   1.0   1.0  17388.5101
35     5   0.5  0.00   1.5   0.0  13910.8081
36     5   0.5  0.00   1.5   0.0  17388.5101
37     5   0.5  0.00   1.5   0.0  20866.2121
38     5   0.5  0.05   1.5   0.0   3477.7020
39     5   0.5  0.05   1.5   0.0   6955.4040
40     5   0.5  0.05   1.5   0.0  10433.1061
41     5   0.5  0.05   1.5   0.0  13910.8081
42     5   0.5  0.05   1.5   0.0  17388.5101
43     5   0.5  0.05   1.5   0.0  20866.2121
44     5   0.5  0.10   1.5   0.0   3477.7020
45     5   0.5  0.10   1.5   0.0   6955.4040
46     5   0.5  0.10   1.5   0.0  10433.1061
47     5   0.5  0.10   1.5   0.0  13910.8081
48     5   0.5  0.10   1.5   0.0  17388.5101
49     5   0.5  0.05   1.0   0.0  20866.2121
50     5   0.5  0.05   1.0   0.0   3477.7020
51     5   0.5  0.05   1.0   0.0   6955.4040
52     5   0.5  0.05   1.0   0.0  10433.1061
53     5   0.5  0.05   1.0   0.0  13910.8081
54     5   0.5  0.05   1.0   0.0  17388.5101
55     5   0.5  0.10   1.0   0.0  20866.2121
56     5   0.5  0.10   1.0   0.0   3477.7020
57     5   0.5  0.10   1.0   0.0   6955.4040
58     5   0.5  0.10   1.0   0.0  10433.1061
59     5   0.5  0.10   1.0   0.0  13910.8081
60     5   0.5  0.10   1.0   0.0  17388.5101

In [11]:
df.to_excel("data/Nusseltdata.xlsx", index=False)