In [1]:
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
df = pd.DataFrame(digits.data,digits.target)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [6]:
df['target'] = digits.target
df.head(20)

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
5,0.0,0.0,12.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,9.0,16.0,16.0,10.0,0.0,0.0,5
6,0.0,0.0,0.0,12.0,13.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,9.0,15.0,11.0,3.0,0.0,6
7,0.0,0.0,7.0,8.0,13.0,16.0,15.0,1.0,0.0,0.0,...,0.0,0.0,0.0,13.0,5.0,0.0,0.0,0.0,0.0,7
8,0.0,0.0,9.0,14.0,8.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,11.0,16.0,15.0,11.0,1.0,0.0,8
9,0.0,0.0,11.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,9.0,12.0,13.0,3.0,0.0,0.0,9
0,0.0,0.0,1.0,9.0,15.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,10.0,13.0,3.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,14.0,13.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,13.0,16.0,1.0,0.0,1
2,0.0,0.0,5.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,3.0,11.0,8.0,13.0,12.0,4.0,2
3,0.0,2.0,9.0,15.0,14.0,9.0,3.0,0.0,0.0,4.0,...,0.0,0.0,2.0,12.0,12.0,13.0,11.0,0.0,0.0,3
4,0.0,0.0,0.0,8.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.0,15.0,4.0,0.0,0.0,4
5,0.0,5.0,12.0,13.0,16.0,16.0,2.0,0.0,0.0,11.0,...,0.0,0.0,4.0,15.0,16.0,2.0,0.0,0.0,0.0,5
6,0.0,0.0,0.0,8.0,15.0,1.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,7.0,15.0,16.0,11.0,0.0,6
7,0.0,0.0,1.0,8.0,15.0,10.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,11.0,9.0,0.0,0.0,0.0,7
8,0.0,0.0,10.0,7.0,13.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,11.0,14.0,5.0,0.0,0.0,0.0,8
9,0.0,0.0,6.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,7.0,16.0,16.0,13.0,11.0,1.0,9

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target',axis='columns'), df.target, test_size=0.3)

**Using RBF kernel**

In [8]:
from sklearn.svm import SVC
rbf_model = SVC(kernel='rbf')

In [9]:
len(X_train)

1257

In [10]:
len(X_test)

540

In [11]:
rbf_model.fit(X_train, y_train)

SVC()

In [12]:
rbf_model.score(X_test,y_test)

0.9851851851851852

**Using Linear kernel**

In [13]:
linear_model = SVC(kernel='linear')
linear_model.fit(X_train,y_train)

SVC(kernel='linear')

In [14]:
linear_model.score(X_test,y_test)

0.9722222222222222

In [15]:
df.shape

(1797, 65)

In [16]:
rbf_model.predict(X_test)

array([3, 0, 2, 8, 1, 5, 6, 1, 8, 5, 9, 9, 4, 3, 2, 3, 2, 9, 9, 5, 5, 3,
       3, 6, 6, 0, 6, 9, 7, 7, 7, 4, 1, 8, 9, 1, 9, 1, 9, 2, 0, 1, 4, 1,
       1, 2, 4, 7, 5, 7, 0, 0, 4, 4, 3, 2, 5, 4, 6, 5, 6, 0, 3, 9, 3, 1,
       3, 3, 7, 2, 3, 4, 6, 3, 3, 9, 9, 3, 7, 4, 7, 3, 7, 1, 6, 5, 8, 8,
       5, 7, 7, 8, 4, 1, 0, 7, 6, 7, 2, 3, 6, 7, 2, 5, 3, 1, 4, 3, 6, 9,
       5, 9, 6, 4, 3, 3, 3, 2, 3, 6, 1, 6, 4, 1, 7, 2, 1, 1, 7, 9, 6, 5,
       4, 3, 6, 0, 6, 0, 2, 1, 8, 4, 4, 2, 1, 9, 7, 1, 3, 3, 8, 2, 1, 3,
       5, 8, 8, 0, 2, 6, 2, 2, 7, 6, 8, 5, 1, 8, 9, 5, 2, 8, 6, 5, 6, 4,
       7, 8, 7, 6, 1, 2, 5, 0, 3, 1, 6, 2, 6, 9, 5, 9, 3, 8, 9, 9, 7, 8,
       4, 7, 9, 5, 3, 2, 5, 4, 9, 4, 8, 2, 4, 8, 4, 6, 1, 9, 7, 4, 6, 8,
       2, 1, 8, 9, 0, 3, 8, 8, 0, 3, 0, 7, 3, 6, 7, 0, 2, 9, 7, 9, 9, 1,
       2, 8, 0, 5, 7, 1, 9, 5, 0, 1, 9, 1, 9, 5, 4, 2, 9, 5, 1, 4, 5, 5,
       2, 5, 7, 2, 3, 0, 1, 6, 5, 3, 5, 4, 4, 7, 0, 9, 2, 9, 3, 5, 9, 2,
       2, 0, 5, 3, 6, 3, 7, 0, 8, 0, 4, 2, 7, 1, 9, 5, 4, 5, 5, 8, 2, 3,
       9, 7, 0, 1, 0, 5, 0, 1, 9, 6, 8, 3, 2, 4, 4, 6, 5, 2, 0, 0, 2, 9,
       2, 9, 5, 2, 7, 3, 2, 6, 4, 7, 4, 4, 9, 5, 0, 7, 2, 4, 3, 3, 1, 3,
       5, 3, 9, 5, 9, 4, 6, 6, 8, 2, 6, 8, 4, 2, 6, 2, 2, 2, 8, 7, 7, 6,
       6, 6, 9, 6, 2, 1, 4, 8, 3, 5, 4, 7, 8, 4, 2, 8, 1, 6, 7, 5, 0, 9,
       5, 8, 6, 4, 3, 8, 7, 2, 9, 4, 8, 5, 6, 5, 7, 4, 2, 9, 1, 5, 5, 4,
       9, 6, 3, 3, 5, 2, 8, 7, 3, 4, 7, 7, 7, 9, 1, 8, 1, 2, 9, 6, 3, 8,
       7, 0, 5, 1, 7, 1, 0, 6, 2, 4, 1, 9, 1, 7, 4, 8, 1, 5, 5, 3, 3, 7,
       0, 2, 6, 0, 0, 0, 0, 0, 2, 5, 5, 6, 1, 9, 6, 7, 8, 5, 0, 3, 6, 6,
       0, 9, 6, 0, 3, 0, 9, 9, 0, 3, 4, 0, 4, 2, 2, 6, 0, 9, 7, 7, 3, 1,
       9, 3, 5, 3, 0, 3, 9, 3, 0, 6, 9, 3, 6, 3, 4, 8, 0, 2, 9, 5, 0, 1,
       3, 8, 2, 5, 9, 4, 3, 2, 2, 5, 0, 6])

In [17]:
X_test

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
3,0.0,0.0,9.0,10.0,2.0,0.0,0.0,0.0,0.0,8.0,...,12.0,0.0,0.0,0.0,8.0,14.0,16.0,15.0,6.0,0.0
0,0.0,0.0,2.0,12.0,15.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,14.0,4.0,0.0,0.0
2,0.0,0.0,0.0,0.0,11.0,15.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,11.0,16.0,12.0,0.0
8,0.0,0.0,1.0,11.0,15.0,6.0,0.0,0.0,0.0,2.0,...,3.0,0.0,0.0,0.0,1.0,15.0,15.0,6.0,0.0,0.0
1,0.0,0.0,0.0,0.0,6.0,16.0,7.0,0.0,0.0,1.0,...,9.0,0.0,0.0,0.0,0.0,0.0,8.0,16.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,0.0,3.0,15.0,16.0,8.0,0.0,0.0,0.0,0.0,9.0,...,13.0,1.0,0.0,3.0,16.0,12.0,8.0,12.0,11.0,1.0
2,0.0,0.0,10.0,16.0,9.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,11.0,16.0,16.0,16.0,2.0,0.0
5,0.0,2.0,12.0,13.0,16.0,16.0,4.0,0.0,0.0,11.0,...,0.0,0.0,0.0,3.0,13.0,15.0,0.0,0.0,0.0,0.0
0,0.0,0.0,4.0,13.0,14.0,8.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,5.0,16.0,14.0,1.0,0.0,0.0
6,0.0,0.0,7.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,15.0,13.0,3.0,0.0,0.0

## Sources

Source: [Codebasics](https://github.com/codebasics/py).