In [1]:
import pandas as pd

In [2]:
path = "data/titanic.csv"

In [3]:
df = pd.read_csv(path)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
dfn = df[['Survived','Pclass','Sex','Age','Fare']]
dfn

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [7]:
bro=pd.crosstab(df['Sex'],df['Survived'])
bro

Survived    0    1
Sex
female     81  233
male      468  109

In [9]:
bro['Percentage_Survived'] = bro[1]/(bro[1]+bro[0])*100
bro['Percentage_Died'] = bro[0]/(bro[1]+bro[0])*100
bro

Survived    0    1  Percentage_Survived  Percentage_Died
Sex
female     81  233            74.203822        25.796178
male      468  109            18.890815        81.109185

In [24]:
fare = dfn.drop(columns='Sex')
fare.groupby('Survived').mean()

            Pclass        Age       Fare
Survived
0         2.531876  30.626179  22.117887
1         1.950292  28.343690  48.395408

In [15]:
inputs = dfn.drop(columns='Survived')
Target = dfn['Survived']
inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()

In [19]:
inputs['sex_n'] = le_sex.fit_transform(inputs['Sex'])
inputs = inputs.drop(columns='Sex')
inputs

     Pclass   Age     Fare  sex_n
0         3  22.0   7.2500      1
1         1  38.0  71.2833      0
2         3  26.0   7.9250      0
3         1  35.0  53.1000      0
4         3  35.0   8.0500      1
..      ...   ...      ...    ...
886       2  27.0  13.0000      1
887       1  19.0  30.0000      0
888       3   NaN  23.4500      0
889       1  26.0  30.0000      1
890       3  32.0   7.7500      1

[891 rows x 4 columns]

In [20]:
inputs = inputs[['Pclass', 'sex_n', 'Age', 'Fare']]

inputs

     Pclass  sex_n   Age     Fare
0         3      1  22.0   7.2500
1         1      0  38.0  71.2833
2         3      0  26.0   7.9250
3         1      0  35.0  53.1000
4         3      1  35.0   8.0500
..      ...    ...   ...      ...
886       2      1  27.0  13.0000
887       1      0  19.0  30.0000
888       3      0   NaN  23.4500
889       1      1  26.0  30.0000
890       3      1  32.0   7.7500

[891 rows x 4 columns]

In [21]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [22]:
model.fit(inputs,Target)

DecisionTreeClassifier()

In [40]:
model.score(inputs, Target)

0.8417508417508418

In [39]:
model.predict([[1,1,40,30]])

array([0], dtype=int64)

In [38]:
model.predict_proba([[1,1,40,30]])

array([[0.55, 0.45]])

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(inputs,Target,train_size=0.9)

In [42]:
x_train

     Pclass  sex_n   Age     Fare
626       2      1  57.0  12.3500
309       1      0  30.0  56.9292
592       3      1  47.0   7.2500
667       3      1   NaN   7.7750
529       2      1  23.0  11.5000
..      ...    ...   ...      ...
234       2      1  24.0  10.5000
692       3      1   NaN  56.4958
439       2      1  31.0  10.5000
559       3      0  36.0  17.4000
499       3      1  24.0   7.7958

[801 rows x 4 columns]

In [47]:
y_train

626    0
309    1
592    0
667    0
529    0
      ..
234    0
692    1
439    0
559    1
499    0
Name: Survived, Length: 801, dtype: int64

In [43]:
x_test

     Pclass  sex_n   Age     Fare
462       1      1  47.0  38.5000
841       2      1  16.0  10.5000
32        3      0   NaN   7.7500
500       3      1  17.0   8.6625
259       2      0  50.0  26.0000
..      ...    ...   ...      ...
551       2      1  27.0  26.0000
293       3      0  24.0   8.8500
612       3      0   NaN  15.5000
482       3      1  50.0   8.0500
72        2      1  21.0  73.5000

[90 rows x 4 columns]

In [45]:
y_test

462    0
841    0
32     1
500    0
259    1
      ..
551    0
293    0
612    1
482    0
72     0
Name: Survived, Length: 90, dtype: int64

In [46]:
model.score(x_test,y_test)

0.8555555555555555

In [48]:
model.predict(x_test)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0], dtype=int64)

## Sources

Source: [Codebasics](https://github.com/codebasics/py).