In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import linear_model

In [4]:
df=pd.read_csv("data/homeprices (2).csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df.bedrooms.median()

4.0

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [9]:
df.bedrooms.fillna(median_bedrooms,inplace=True)

In [10]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df.at[2, 'bedrooms'] = 3.0

In [12]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [17]:
reg.coef_

array([  119.67905405, 13097.24903475, -4207.28764479])

In [19]:
reg.intercept_

256461.14864864887

In [20]:
df = df.drop(df.index[-1])
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [22]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [23]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [24]:
reg.intercept_

383724.9999999998

In [28]:
reg.predict([[3000,3,40]])

array([444400.])

In [29]:
reg.predict([[2500,4,5]])

array([588625.])

In [31]:
reg.predict([[4000,5,8]])

array([748000.])

In [32]:
hiringdf=pd.read_csv("data/hiring.csv")
hiringdf

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [48]:
from word2number import w2n

hiringdf['experience'] = hiringdf['experience'].fillna('zero')

hiringdf['experience'] = hiringdf['experience'].apply(lambda value: w2n.word_to_num(value) if isinstance(value, str) else value)

median_test_score = round(hiringdf['test_score(out of 10)'].median())

hiringdf['test_score(out of 10)'] = hiringdf['test_score(out of 10)'].fillna(median_test_score)

In [40]:
hiringdf

In [43]:
regex = linear_model.LinearRegression()
regex.fit(hiringdf[['experience','test_score(out of 10)','interview_score(out of 10)']],hiringdf['salary($)'])

In [46]:
regex.predict([[2,9,6]])

In [47]:
regex.predict([[12,10,10]])