In [30]:
import pandas as pd

In [31]:
df=pd.read_csv("data/music.csv")

In [32]:
df

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [33]:
x=df.drop(columns=['genre'])
y=df['genre']

In [34]:
x

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [35]:
y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: object

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
model=DecisionTreeClassifier()

In [38]:
model.fit(x,y)

DecisionTreeClassifier()

In [39]:
df

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [40]:
predictions=model.predict([[21,1],[22,0]])
predictions

array(['HipHop', 'Dance'], dtype=object)

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2)
model.fit(x_train,y_train)
predictions=model.predict(x_test)
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,predictions)
score

0.5

In [44]:
import joblib
model.fit(x,y)
joblib.dump(model,'dfreco.joblib')

In [46]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib

df=pd.read_csv("data/music.csv")
x=df.drop(columns=['genre'])
y=df['genre']

model=DecisionTreeClassifier()
model.fit(x,y)

joblib.dump(model,'dfreco.joblib')